import { ILobbySettings } from './ISettings';

export const defaultLobbySettings: ILobbySettings = {
	maxDistance: 5.32,
	haunting: false,
	snrJumboVoice: false,
	jackalHaunting: false,
	jackalHearOutsideVents: false,
	jackalTalkInVents: false,
	jackalRadioEnabled: false,
	sidekickHaunting: false,
	sidekickHearOutsideVents: false,
	sidekickTalkInVents: false,
	nosNeutralKillerHaunting: false,
	nosVoicePositions: false,
	nosSizeVoiceEffect: true,
	nosBerserkerVoiceEffect: true,
	nosRokurokubiVoiceEffect: true,
	nosCitrusVoiceEffect: true,
	nosRainbowStarEcho: true,
	nosFixerJammingVoiceBlock: true,
	nosFixerJammingLowpass: false,
	tohNeutralKillerHaunting: false,
	hearImpostorsInVents: false,
	impostersHearImpostersInvent: false,
	impostorRadioEnabled: false,
	impostorRadioOnlyMode: false,
	commsSabotage: false,
	voiceEffectEnabled: true,
	deadOnly: false,
	hearThroughCameras: false,
	wallsBlockAudio: false,
	meetingGhostOnly: false,
	visionHearing: false,
	publicLobby_on: false,
	publicLobby_title: '',
	publicLobby_language: 'ja',
};
