name: Release 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
         - os: windows-latest
           dist: 'publish'
           installer: |
             dist/Better-CrewLinkKai-Setup*.exe
             dist/latest.yml
         - os: ubuntu-latest
           dist: 'publish:linux'
           installer: |
             dist/Better-CrewLinkKai-*.AppImage
             dist/latest-linux.yml

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb1-dev libx11-dev
    
      - name: Install Dependencies
        run: yarn install --cache-folder .yarn --network-timeout 100000
        
      - name: Build App
        run: yarn run ${{ matrix.dist }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: BetterCrewLink Installer ${{ runner.os }}
          path: ${{ matrix.installer }}
          if-no-files-found: error
          
      - name: Upload Unpacked 64bit
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          name: BetterCrewLink Unpacked 64bit 
          path: 'dist/win-unpacked'
          
      - name: Upload Unpacked 32bit
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          name: BetterCrewLink Unpacked 32bit 
          path: 'dist/win-ia32-unpacked'
